# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(19191E)
$foreground = rgb(F1EBED)
$color0 = rgb(403F46)
$color1 = rgb(101126)
$color2 = rgb(593B54)
$color3 = rgb(92536B)
$color4 = rgb(B86F67)
$color5 = rgb(6C8997)
$color6 = rgb(A19598)
$color7 = rgb(E3DBDD)
$color8 = rgb(9F999A)
$color9 = rgb(161633)
$color10 = rgb(774E70)
$color11 = rgb(C26F8F)
$color12 = rgb(F69489)
$color13 = rgb(90B7C9)
$color14 = rgb(D7C7CB)
$color15 = rgb(E3DBDD)
