# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6F0F3
background         #050019
cursor             #8A90CD

active_tab_foreground     #050019
active_tab_background     #F6F0F3
inactive_tab_foreground   #F6F0F3
inactive_tab_background   #050019

active_border_color   #F6F0F3
inactive_border_color #050019
bell_border_color     #16247E

color0      #050019
color1		#16247E
color2		#16247E
color3		#16247E
color4		#5355A6
color5		#836EA3
color6		#AC9EA5
color7		#EAE1E5
color8		#A39DA0
color9		#1E30A8
color10		#1E30A8
color11		#1E30A8
color12		#6F71DD
color13		#AE93D9
color14		#E5D3DC
color15		#EAE1E5
