# yazi.toml
[mgr]
show_hidden = true
#sort_by = "mtime"
sort_reverse = true
linemode = "size_and_mtime"

[plugin]
prepend_previewers = [
{ mime = "audio/*",   run = "exifaudio"},
{ mime = "application/*zip", run = "ouch" },
{ name = "*.zip", run = "ouch" },
{ name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
{ name = "*.csv", run  = 'piper -- bat -p --color=always "$1"'},
{ name = "*/", run  = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'},
]

# [opener]
# extract = [
# 	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
# ]

[[plugin.prepend_fetchers]]
id   = "mime"
name = "*"
run  = "mime-ext"
prio = "high"

# git.yazi
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
